In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
dataset=pd.read_csv("diabetes.csv",index_col=None)
dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
dataset.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [4]:
indep_X=dataset[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age',]]
dep_Y=dataset['Outcome']

In [5]:
dep_Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [9]:

dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

def LDA(X_train, X_test,y_train):
        from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
        lda = LDA(n_components = 1)
        X_train1 = lda.fit_transform(X_train,y_train)
        X_test1 = lda.transform(X_test)
        print("lda:",lda)
        return X_train1,X_test1,y_train
    
def cm_prediction(classifier,X_test1):
        y_pred = classifier.predict(X_test1)
        
        # Making the Confusion Matrix
        from sklearn.metrics import confusion_matrix
        cm = confusion_matrix(y_test, y_pred)
        
        from sklearn.metrics import accuracy_score 
        from sklearn.metrics import classification_report 
        
        Accuracy=accuracy_score(y_test, y_pred)
        report=classification_report(y_test, y_pred)
        
        return  classifier,Accuracy,report,X_test1,y_test,cm

def logistic(X_train1,y_train,X_test1):
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm      
    
def svm_linear(X_train1,y_train,X_test1):              
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def svm_NL(X_train1,y_train,X_test1):             
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm

def Navie(X_train1,y_train,X_test1):       
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm         
    
def knn(X_train1,y_train,X_test1):
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def Decision(X_train1,y_train,X_test1):
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm      


def random(X_train1,y_train,X_test1):
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['LDA'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [11]:
X_train, X_test, y_train, y_test = split_scalar(indep_X,dep_Y)

In [12]:
LDA = LDA(X_train, X_test,y_train)
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

lda: LinearDiscriminantAnalysis(n_components=1)

In [13]:
LDA

(array([[-1.26652465e+00],
        [-3.53050099e-01],
        [-1.20333632e+00],
        [ 1.74073116e+00],
        [ 1.52743818e+00],
        [ 5.37142339e-01],
        [-1.53399663e+00],
        [-3.60406721e-02],
        [-1.40442284e+00],
        [-8.50636948e-01],
        [-5.93787827e-01],
        [ 3.50993203e-01],
        [-3.08268125e-01],
        [-7.47345825e-01],
        [-3.47872968e-01],
        [-5.66850745e-01],
        [ 2.05175977e-01],
        [-9.80954478e-01],
        [-1.03304831e+00],
        [-1.30008476e+00],
        [ 1.26607395e-01],
        [-1.16706650e-01],
        [-4.68071337e-01],
        [ 1.05970163e-01],
        [ 4.40560479e-01],
        [-6.54140567e-02],
        [ 7.18199178e-01],
        [-3.71648864e-01],
        [-9.07171012e-01],
        [-1.73988906e+00],
        [ 5.72965108e-01],
        [ 1.16450542e+00],
        [ 9.07003703e-01],
        [ 1.32632421e+00],
        [-2.63307990e-01],
        [-2.37064098e-01],
        [-1.62842272e+00],
        [-6.66979578e-01],
        [ 4.16542639e-01],
        [ 8.27182105e-01],
        [-2.08799720e+00],
        [ 7.10895285e-02],
        [ 1.55500218e+00],
        [ 1.70323397e-01],
        [-6.06106376e-01],
        [ 2.07046365e+00],
        [-6.43983155e-01],
        [ 2.55091984e+00],
        [ 1.42788515e-01],
        [ 6.97088457e-01],
        [-5.68229399e-01],
        [-3.08461074e-01],
        [-5.65957873e-01],
        [ 4.06211149e-01],
        [-6.51854168e-01],
        [ 1.47868527e+00],
        [ 8.00602231e-02],
        [ 3.46311639e-01],
        [ 5.33773041e-02],
        [ 1.07089804e+00],
        [-1.84495306e+00],
        [ 6.60022950e-01],
        [-1.29429821e-01],
        [ 3.03750662e+00],
        [ 1.32540467e-01],
        [-4.56782404e-03],
        [-9.01888906e-01],
        [-1.41748750e-02],
        [-1.62230685e-01],
        [-1.61342416e+00],
        [-5.64642054e-01],
        [-1.24859065e-01],
        [ 1.63146002e+00],
        [-2.42044840e+00],
        [ 1.60626629e-01],
        [ 2.50029174e+00],
        [-1.36885453e-01],
        [-1.29676307e+00],
        [-1.68838641e+00],
        [-2.23351581e+00],
        [-4.19335738e-01],
        [ 6.00978780e-01],
        [ 4.95306706e-01],
        [ 3.26220874e-01],
        [-2.32509864e+00],
        [-5.70799688e-02],
        [ 2.91601619e-01],
        [-9.28964542e-01],
        [-5.77335652e-01],
        [ 7.93738109e-01],
        [ 6.79087784e-02],
        [-7.79768682e-01],
        [-4.08431772e-01],
        [-1.30455508e+00],
        [-2.86343054e+00],
        [-1.31061318e+00],
        [-1.00702535e+00],
        [ 1.81389419e+00],
        [ 1.24660982e+00],
        [ 6.12395144e-02],
        [-4.31048862e-01],
        [ 1.38190199e+00],
        [-5.83687509e-01],
        [ 3.00427396e+00],
        [ 2.89046602e+00],
        [-1.23841975e+00],
        [-1.14047717e+00],
        [ 6.99539340e-01],
        [-5.35851259e-01],
        [ 8.72367133e-01],
        [-1.20876595e+00],
        [-1.61898305e+00],
        [ 9.58109030e-01],
        [ 1.43384364e+00],
        [ 3.85503140e-01],
        [ 6.17681881e-01],
        [-2.16689941e-01],
        [-1.64366678e+00],
        [ 4.87412682e-01],
        [-1.56225199e-01],
        [-6.87746245e-01],
        [ 1.24057247e+00],
        [-6.38741248e-01],
        [-1.40563175e+00],
        [-9.51336982e-01],
        [ 7.12815966e-01],
        [ 2.32029465e+00],
        [ 4.11240712e-01],
        [ 3.59056225e-01],
        [-3.86776979e-02],
        [-1.94134621e+00],
        [ 7.04145681e-01],
        [-3.13911777e-01],
        [ 1.47045996e+00],
        [ 8.87999487e-01],
        [-3.48149898e-01],
        [-1.25465727e+00],
        [ 1.27054761e+00],
        [ 1.70964111e+00],
        [ 1.44866927e+00],
        [ 9.77028074e-01],
        [ 1.97350177e-01],
        [-1.66796644e+00],
        [-1.48108683e+00],
        [-1.43645470e-01],
        [-9.88739416e-01],
        [ 2.04301652e+00],
        [-5.91683312e-01],
        [ 1.27194015e+00],
        [ 9.00043201e-03],
        [ 1.94370485e-01],
        [ 1.92449304e+00],
        [ 1.31190395e+00],
        [-1.39528571e+00],
        [ 2.62874495e-01],
        [ 5.41739196e-01],
        [ 1.62484778e+00],
        [ 2.69340481e+00],
        [-1.28358355e-01],
        [ 9.90513590e-02],
        [-2.42684479e-01],
        [-5.12057993e-01],
        [-1.45180334e+00],
        [ 1.21141198e+00],
        [ 4.71486941e-01],
        [-9.69210408e-01],
        [-2.44589972e-01],
        [-1.42820073e+00],
        [ 1.83892240e+00],
        [ 1.24677019e+00],
        [ 3.37986125e-01],
        [-8.47801376e-01],
        [ 4.50364842e-01],
        [ 4.96825437e-01],
        [ 2.23817322e+00],
        [-3.05225609e-01],
        [-9.39649854e-01],
        [ 2.04729432e+00],
        [ 6.23604467e-01],
        [-1.27117944e+00],
        [-8.57095267e-01],
        [ 8.06506790e-01],
        [-3.48721917e+00],
        [ 1.73214363e+00],
        [ 1.45313990e-01],
        [-1.00553955e+00],
        [-1.49746191e-01],
        [ 2.77400963e+00],
        [ 9.90585925e-01],
        [-1.34942939e+00],
        [ 4.52126992e-02],
        [ 7.75567014e-01],
        [ 1.36498464e+00],
        [ 5.44200953e-01],
        [ 1.66869358e+00],
        [-3.29578603e-01],
        [ 1.74291725e+00],
        [-1.28488009e+00],
        [-9.38505816e-01],
        [-6.25953115e-01],
        [ 1.83453112e+00],
        [-6.32749548e-01],
        [ 2.19754752e+00],
        [-2.76047797e+00],
        [-2.13423848e+00],
        [-6.42857147e-01],
        [ 1.28819960e+00],
        [-4.21980690e-02],
        [ 1.45088398e+00],
        [ 1.97028587e+00],
        [-1.04740576e+00],
        [ 1.79339122e+00],
        [ 1.28652266e+00],
        [-6.90038199e-01],
        [-3.30343630e-02],
        [-4.85900537e-01],
        [ 1.34635911e-01],
        [-6.67098499e-01],
        [-3.49793900e-01],
        [ 1.77320167e+00],
        [ 4.45305145e-01],
        [ 1.36306832e+00],
        [-1.59367658e+00],
        [-9.89755962e-01],
        [-8.11406490e-01],
        [ 2.83972815e+00],
        [ 8.62099479e-01],
        [-4.03506013e-01],
        [ 4.97112997e-01],
        [-1.97169004e-01],
        [ 1.59947664e+00],
        [-6.61438747e-01],
        [-6.29802464e-02],
        [ 3.67936035e-01],
        [-3.09753701e-01],
        [ 1.49822595e+00],
        [-7.46312971e-01],
        [-1.57775857e+00],
        [-1.10909577e+00],
        [ 2.29050381e+00],
        [-1.21929453e+00],
        [ 6.55764533e-01],
        [ 1.20674909e+00],
        [-1.14220008e+00],
        [ 7.97531988e-01],
        [ 1.84517984e-01],
        [-1.18906447e+00],
        [ 1.89188133e-01],
        [-1.50606141e+00],
        [ 2.00375754e-01],
        [ 2.17268899e+00],
        [-1.46177350e+00],
        [-3.42882253e-01],
        [ 2.28132417e+00],
        [-7.32721257e-01],
        [ 4.08983638e-01],
        [-9.26481581e-01],
        [ 2.67881817e+00],
        [ 2.30700262e-01],
        [-7.73872385e-01],
        [ 7.75846358e-02],
        [ 9.72952764e-01],
        [-1.71928917e-01],
        [-6.67744961e-02],
        [ 1.65520122e+00],
        [-4.47684931e-02],
        [ 2.53107501e+00],
        [ 4.18652151e-01],
        [-5.50917405e-01],
        [-7.37701272e-01],
        [ 1.20742356e+00],
        [-2.59618365e+00],
        [ 1.82872756e+00],
        [ 7.67212175e-01],
        [ 2.94238470e-01],
        [ 1.34077585e+00],
        [ 1.06916959e+00],
        [-1.43672277e-01],
        [-2.99774899e-02],
        [-1.11068582e+00],
        [ 2.22692412e+00],
        [-3.13541146e+00],
        [-2.10891577e-03],
        [ 1.36039739e+00],
        [-3.26089856e-01],
        [ 2.28376936e+00],
        [-1.03017341e+00],
        [-7.83285917e-01],
        [ 5.11340054e-01],
        [ 7.29198019e-02],
        [ 1.51856112e+00],
        [-1.32557000e-01],
        [-1.34133107e+00],
        [ 4.82716731e-02],
        [ 1.49799618e+00],
        [ 1.90840445e+00],
        [-1.12802474e+00],
        [ 1.21280644e+00],
        [ 6.02262148e-01],
        [ 1.06507100e-01],
        [ 1.54127099e-01],
        [-5.38877758e-01],
        [-1.04472599e-01],
        [-2.28873572e+00],
        [ 3.66876266e-01],
        [ 9.48952838e-02],
        [ 9.88986017e-01],
        [-9.01978081e-01],
        [ 1.38994541e+00],
        [-1.71441568e-01],
        [ 3.60194670e-01],
        [-9.47391244e-01],
        [-4.87683133e-02],
        [-4.66727730e-01],
        [ 9.38611948e-02],
        [ 9.02080335e-01],
        [ 1.89291939e+00],
        [ 8.62457694e-01],
        [-1.21033365e-01],
        [ 6.33552324e-01],
        [-1.23801106e+00],
        [ 1.12753032e-01],
        [-4.25920988e-01],
        [-1.46878399e+00],
        [ 1.58930281e+00],
        [-1.52712840e+00],
        [ 2.42652431e-01],
        [ 2.37044399e-02],
        [-9.57980417e-02],
        [ 8.00294072e-01],
        [-5.23518465e-01],
        [ 2.34507498e+00],
        [ 2.53882886e-02],
        [-1.27392120e+00],
        [ 1.90000220e-01],
        [-6.09635350e-01],
        [ 1.35560224e+00],
        [-6.32571056e-01],
        [-1.36385472e+00],
        [-8.25539806e-02],
        [-1.71852805e-01],
        [ 1.43318821e+00],
        [-8.99375716e-01],
        [ 6.37232548e-01],
        [-8.83601587e-01],
        [-3.74835523e-01],
        [-4.44630788e-01],
        [-1.76316912e+00],
        [ 1.75244739e+00],
        [ 1.08193229e+00],
        [-8.93237877e-01],
        [-1.03405196e+00],
        [ 1.92464295e-01],
        [-9.94596784e-01],
        [-1.20366484e+00],
        [-7.98273471e-01],
        [-1.37821832e-01],
        [ 8.01421364e-01],
        [-1.45479883e+00],
        [-3.40029251e-01],
        [-1.21507047e+00],
        [-1.89366096e+00],
        [-1.90610080e+00],
        [ 1.44101175e+00],
        [ 9.33488517e-01],
        [-1.12794262e+00],
        [ 5.48751694e-01],
        [-8.52683010e-01],
        [ 2.86253879e-01],
        [-8.71931906e-01],
        [-9.08267923e-01],
        [ 1.07554377e+00],
        [-5.69875596e-01],
        [-2.55267373e-01],
        [-7.58852284e-01],
        [-2.17378813e-02],
        [-1.73510363e-02],
        [ 7.07374918e-01],
        [-4.31599724e-01],
        [ 7.21083928e-01],
        [ 1.10823103e-01],
        [ 5.56225810e-01],
        [-9.28729792e-01],
        [-1.37228641e+00],
        [-1.81361805e-01],
        [ 1.98226596e+00],
        [ 3.30298835e-01],
        [-3.65647238e-01],
        [ 2.90066864e-01],
        [ 1.14432071e+00],
        [-1.66701467e+00],
        [ 5.53406536e-01],
        [ 1.26635395e+00],
        [-1.70583345e+00],
        [-6.03080328e-03],
        [-4.49683734e-01],
        [-2.55522478e+00],
        [ 1.32357046e+00],
        [ 4.42925780e-01],
        [ 1.23583219e+00],
        [-2.08522500e+00],
        [-9.89159479e-02],
        [ 4.98837976e-01],
        [-2.34940530e-01],
        [-2.71163737e-01],
        [ 1.86206917e+00],
        [-1.68406045e+00],
        [ 5.31274137e-01],
        [ 1.78229589e+00],
        [ 1.38208084e-01],
        [-9.39074934e-02],
        [-2.24526502e-01],
        [ 2.99548442e+00],
        [ 1.17713149e+00],
        [ 4.23490637e+00],
        [-8.08236896e-01],
        [-1.92071581e-01],
        [ 4.07998385e-01],
        [ 9.65267697e-01],
        [-1.65192416e+00],
        [ 1.82343434e+00],
        [-6.44616631e-01],
        [-2.27311351e+00],
        [ 1.20372025e+00],
        [-5.26946994e-01],
        [ 1.54067655e+00],
        [ 1.33286744e+00],
        [-2.48892443e-01],
        [ 3.13946376e-01],
        [-2.10908084e+00],
        [-1.54692162e-01],
        [-1.75631187e+00],
        [-1.67591578e-01],
        [-3.32951991e-01],
        [-4.09673079e-02],
        [ 6.41356167e-01],
        [-9.76653049e-01],
        [-1.94530318e-01],
        [ 7.39267152e-01],
        [ 5.19382365e-01],
        [ 1.07550437e+00],
        [-1.78833657e+00],
        [-3.41819636e-01],
        [-2.73740585e-01],
        [ 1.38953099e-01],
        [-1.67613897e+00],
        [ 1.73030871e+00],
        [ 1.26939328e+00],
        [-2.25801330e-02],
        [-3.49062788e-01],
        [-3.97471776e+00],
        [-1.62464842e+00],
        [-1.01119473e+00],
        [-8.02148595e-01],
        [ 1.98191600e+00],
        [ 2.48809588e+00],
        [ 7.07447594e-01],
        [ 8.90701465e-01],
        [ 1.77805029e+00],
        [ 1.05340132e+00],
        [-4.64051970e-01],
        [-8.85597929e-01],
        [ 2.10121123e+00],
        [ 1.12294735e+00],
        [ 4.33762662e-01],
        [ 3.34143394e-01],
        [ 2.46228076e-02],
        [-8.14232323e-01],
        [-7.81430839e-01],
        [ 1.03218024e+00],
        [-8.65537819e-02],
        [-1.45110751e-01],
        [-3.13066261e-01],
        [ 2.31621587e+00],
        [-6.92454302e-01],
        [-1.00134031e+00],
        [ 3.32689242e-01],
        [-1.87749794e+00],
        [-9.33308380e-01],
        [-7.21359428e-01],
        [ 4.34064493e-01],
        [ 1.09644153e+00],
        [-1.76026913e-01],
        [ 2.01283519e+00],
        [-9.86457710e-01],
        [ 7.16451986e-01],
        [-6.48748433e-01],
        [ 2.34702288e+00],
        [-8.58715253e-01],
        [-7.12611332e-01],
        [ 5.71606870e-02],
        [ 3.85476721e-01],
        [-4.96088483e-01],
        [ 1.58846383e+00],
        [ 1.21195568e+00],
        [ 1.12764283e-01],
        [-1.71257456e+00],
        [ 9.51533408e-01],
        [-1.29238361e+00],
        [-1.73596377e+00],
        [-5.13953602e-01],
        [-1.69646319e+00],
        [ 1.01309866e+00],
        [-9.54505386e-01],
        [-1.09180388e+00],
        [ 1.52477980e+00],
        [-2.00525692e+00],
        [-1.64455769e-01],
        [-7.76246266e-01],
        [-1.08939294e+00],
        [-1.56904669e+00],
        [-2.01420148e-01],
        [ 3.37749804e-01],
        [-5.96283477e-01],
        [-8.37172858e-01],
        [-9.29812921e-03],
        [-3.03943751e-01],
        [-8.34058112e-01],
        [-2.49518980e+00],
        [ 8.26336049e-01],
        [ 1.49122708e+00],
        [-1.61425085e+00],
        [-1.16386924e+00],
        [-9.22913073e-01],
        [ 1.93049958e+00],
        [-4.01045197e-01],
        [-3.05621024e-01],
        [ 7.47316660e-01],
        [-1.69743554e+00],
        [ 1.15664717e+00],
        [-3.74771630e-01],
        [ 1.82905499e+00],
        [-7.62362531e-01],
        [ 6.40255316e-01],
        [-1.05308429e+00],
        [-1.03162741e+00],
        [-1.26127333e+00],
        [-1.89161283e+00],
        [-9.77003659e-01],
        [-3.02970213e-02],
        [-1.42502728e+00],
        [-4.99465094e-01],
        [ 7.44533595e-02],
        [-6.59346388e-01],
        [ 1.54973892e+00],
        [ 6.01846780e-01],
        [-6.56834128e-01],
        [-9.47080307e-01],
        [-5.11340922e-01],
        [ 8.74029025e-01],
        [ 1.43310369e+00],
        [-1.76952287e+00],
        [-1.02907394e+00],
        [ 1.28969759e+00],
        [-1.47108878e+00],
        [-4.73058934e-01],
        [-1.08008383e+00],
        [ 4.78282023e-01],
        [-7.14725555e-01],
        [ 7.26358126e-01],
        [-6.07096059e-01],
        [-1.19014701e+00],
        [-1.21391717e-01],
        [-4.50821819e-01],
        [-9.78307932e-01],
        [ 1.37404341e+00],
        [-1.13893398e+00],
        [ 2.67008697e-01],
        [-1.68851248e+00],
        [ 2.09093932e+00],
        [-1.93656482e-01],
        [ 2.46419302e-01],
        [ 1.08639732e+00],
        [-1.47550313e+00],
        [-7.46324674e-01],
        [-9.41073866e-01]]),
 array([[ 3.00444479e+00],
        [-6.51499068e-01],
        [-1.21805611e+00],
        [ 1.13623570e+00],
        [-9.05312035e-01],
        [-1.88230798e+00],
        [ 1.45724823e+00],
        [ 2.02276948e+00],
        [ 3.09138002e-01],
        [ 2.37825239e-01],
        [ 9.00252534e-01],
        [ 3.08139394e+00],
        [-4.50097388e-02],
        [-5.80973619e-01],
        [-9.14848860e-01],
        [-6.54456585e-01],
        [ 2.07149474e+00],
        [-2.17873498e+00],
        [ 4.69958117e-01],
        [-2.46620813e-01],
        [ 1.10759608e+00],
        [ 2.42559272e-01],
        [-4.18562814e-01],
        [-1.44890762e+00],
        [-1.60944159e+00],
        [ 1.22191977e-01],
        [-1.69987432e+00],
        [ 2.37839253e+00],
        [-9.76725289e-01],
        [-7.88487341e-01],
        [ 5.82510666e-01],
        [-2.73073666e-01],
        [-1.10816788e+00],
        [ 4.86834976e-01],
        [-1.05717113e+00],
        [ 1.28664590e+00],
        [ 5.37012710e-01],
        [-1.18743804e+00],
        [ 6.90097690e-02],
        [ 1.41813963e+00],
        [-1.37168011e-01],
        [-5.01626137e-01],
        [-6.60656939e-01],
        [ 1.80070425e+00],
        [ 1.64302745e+00],
        [-2.88304249e+00],
        [-1.19562451e+00],
        [-4.01505307e-01],
        [ 1.51996411e-01],
        [-8.79969790e-02],
        [ 2.91841255e-01],
        [-5.39726097e-01],
        [ 2.12324640e+00],
        [ 6.20848861e-01],
        [-8.15897523e-01],
        [-3.97163759e+00],
        [-1.46970732e+00],
        [ 6.18920593e-01],
        [-1.66754619e-01],
        [-1.27225766e+00],
        [ 1.42956477e+00],
        [ 5.49103422e-01],
        [-1.03090837e+00],
        [ 1.23382838e+00],
        [ 1.19564384e+00],
        [ 2.36846811e+00],
        [ 1.33944827e+00],
        [-7.43586325e-01],
        [ 1.25444720e-01],
        [-1.01466821e+00],
        [-9.54700052e-01],
        [ 2.71746255e-01],
        [-1.12810496e+00],
        [ 2.86797242e+00],
        [ 1.83806367e+00],
        [-1.20262401e-02],
        [-9.72155101e-01],
        [ 1.08538972e+00],
        [-1.36275900e+00],
        [-5.37711285e-01],
        [ 4.13909196e-03],
        [ 2.99637443e-01],
        [-4.10949719e-01],
        [-1.97356552e+00],
        [-4.82907119e-01],
        [-4.99423505e-01],
        [-1.21981265e-01],
        [ 2.89192923e-01],
        [ 2.16631662e+00],
        [-5.75816970e-01],
        [-6.00492623e-01],
        [-5.87511037e-01],
        [-3.45512581e-01],
        [-1.79500949e+00],
        [ 1.16329412e+00],
        [-5.26522177e-01],
        [ 3.35121803e-01],
        [ 6.89736518e-01],
        [ 1.03664526e+00],
        [-2.51429943e-01],
        [-2.18921744e-01],
        [-1.14934397e+00],
        [-4.42118994e-01],
        [-1.85982313e+00],
        [ 9.93593813e-01],
        [ 1.03443093e-01],
        [-7.83982935e-01],
        [-4.15734960e-02],
        [-1.74882171e+00],
        [ 1.48140043e+00],
        [-1.04896137e+00],
        [ 1.44412203e-03],
        [ 9.36870938e-01],
        [ 3.47498171e-01],
        [ 7.85840148e-01],
        [ 9.94083845e-01],
        [-9.60478194e-01],
        [ 1.19271123e+00],
        [-1.09051665e+00],
        [ 1.45961339e+00],
        [ 2.13492100e-01],
        [ 2.43018415e-01],
        [-8.35744431e-02],
        [ 5.28691073e-01],
        [-3.71151561e-01],
        [-1.74574680e+00],
        [ 8.88387189e-03],
        [ 1.58343424e-01],
        [ 5.90021552e-01],
        [ 2.02446927e-01],
        [ 2.30068677e-01],
        [-1.81578222e+00],
        [-1.55632261e+00],
        [ 1.57800598e+00],
        [-4.57736697e-02],
        [ 3.15510451e-01],
        [-8.22794389e-01],
        [ 1.92274826e-01],
        [ 1.05239040e+00],
        [-4.91828804e-01],
        [-1.21962912e+00],
        [ 7.71309674e-01],
        [-1.42497819e+00],
        [-1.34284359e+00],
        [ 8.05532110e-02],
        [-1.23252183e+00],
        [-1.33203324e+00],
        [-1.12837091e+00],
        [-8.51850435e-01],
        [-4.54656410e-01],
        [-1.26450195e+00],
        [ 1.00303153e+00],
        [-1.04590670e+00],
        [-5.71706124e-01],
        [ 1.58014847e+00],
        [-9.18906567e-01],
        [ 1.30259735e+00],
        [-8.00571985e-01],
        [ 6.63180544e-01],
        [ 2.92754216e+00],
        [ 1.18094920e+00],
        [ 1.62974984e+00],
        [-2.32824914e+00],
        [-2.31049486e-01],

In [14]:
X_train1,X_test1,y_train=LDA

In [15]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train1,y_train,X_test1)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train1,y_train,X_test1)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train1,y_train,X_test1)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train1,y_train,X_test1)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train1,y_train,X_test1)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train1,y_train,X_test1)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train1,y_train,X_test1)  
accrf.append(Accuracy)
    
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18192\618082569.py:85: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Logistic'][idex]=acclog[number]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18192\618082569.py:86: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMl'][idex]=accsvml[number]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18192\618082569.py:87: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMnl'][idex]=accsvmnl[number]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18192\618082569.py:88: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['KNN'][idex]=accknn[number]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18192\618082569.py:89: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Navie'][idex]=accnav[number]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18192\618082569.py:90: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Decision'][idex]=accdes[number]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18192\618082569.py:91: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Random'][idex]=accrf[number]

In [16]:
result

     Logistic      SVMl     SVMnl       KNN     Navie  Decision Random
LDA  0.802083  0.802083  0.802083  0.770833  0.802083  0.755208   0.75